services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    environment:
      - LITELLM_MASTER_KEY=DUMMY_LITELLM_MASTER_KEY
      - AWS_ACCESS_KEY_ID=DUMMY_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=DUMMY_AWS_SECRET_ACCESS_KEY
      - AWS_BEDROCK_REGION_NAME=us-west-2
      - DYNAMODB_TABLE=DUMMY_DYNAMODB_TABLE
      - DYNAMODB_REGION_NAME=DUMMY_DYNAMODB_REGION_NAME
      - SQS_URL=DUMMY_SQS_URL
      - SQS_REGION_NAME=DUMMY_SQS_REGION_NAME
      - NO_DOCS=true
      - DISABLE_ADMIN_UI=true
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./plugins/auth_handler.py:/app/auth_handler.py
      - ./plugins/callback_handler.py:/app/callback_handler.py
    command: ["--config", "/app/config.yaml"]

  nginx:
    image: nginx:stable
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/ramdisk/https.pem:/etc/nginx/certs/fullchain.pem
      - /mnt/ramdisk/https.key:/etc/nginx/certs/privkey.pem
    depends_on:
      - litellm
